name: sample-workflow
on: [push]
jobs:
  explore-first-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ˜ The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: echo "ğŸš• The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸš© The workflow is now ready to test your code on the runner"
      - name: List the files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ’ This job's status is ${{ job.status }}."
    
